# Generated by Django 5.0.4 on 2026-04-25 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('urgences_disponibles', models.BooleanField(default=True)),
                ('specialites', models.JSONField(default=list)),
                ('temps_attente_min', models.IntegerField(default=0)),
                ('node_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('depart_lat', models.FloatField()),
                ('depart_lng', models.FloatField()),
                ('hopitaux_consideres', models.JSONField()),
                ('raison_choix', models.TextField()),
                ('eta_minutes', models.FloatField()),
                ('nb_noeuds_explores', models.IntegerField()),
                ('temps_calcul_ms', models.IntegerField()),
                ('path_geojson', models.JSONField()),
                ('hopital_choisi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.hospital')),
            ],
        ),
    ]
