# Generated by Django 5.0.4 on 2026-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeauditlog',
            name='depart_nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
