# Generated by Django 5.0.4 on 2026-04-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_routeauditlog_depart_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='routeauditlog',
            name='destination_changee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routeauditlog',
            name='fraicheur_donnees',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='routeauditlog',
            name='recalculs',
            field=models.JSONField(default=list),
        ),
    ]
